package my.company.best.shop.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7.redhat-1
 * 2014-12-07T00:00:45.142+02:00
 * Generated source version: 2.7.7.redhat-1
 * 
 */
@WebService(targetNamespace = "http://ws.shop.best.company.my/", name = "AccountManagementWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface AccountManagementWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAccount", targetNamespace = "http://ws.shop.best.company.my/", className = "my.company.best.shop.client.GetAccount")
    @WebMethod
    @ResponseWrapper(localName = "getAccountResponse", targetNamespace = "http://ws.shop.best.company.my/", className = "my.company.best.shop.client.GetAccountResponse")
    public my.company.best.shop.client.AccountDTO getAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
